services:
  - type: worker
    name: discord-music-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: DISCORD_API_TOKEN
        sync: false
